version: '3.8'

services:
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: login_db
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 60s
      retries: 20
      interval: 10s
    networks:
      - mynetwork

  backend1:
    image: mi:backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/login_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: rootpassword
    depends_on:
      db:
        condition: service_healthy
    networks:
      - mynetwork


  frontend:
    image: abhilashsivaraman/react-spring:frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend1
    networks:
      - mynetwork